services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learning_net

  app:
    build:
      context: .
      args:
        - APP_VERSION=2.0.0
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/app_db?sslmode=disable"
      APP_VERSION: "Learning_EM_T9"
    networks:
      - learning_net

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./pages:/usr/share/nginx/html:ro
    networks:
      - learning_net

networks:
  learning_net:
    driver: bridge
volumes:
  postgres_data: