#building and starting app
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/app_db?sslmode=disable"

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./pages:/usr/share/nginx/html:ro

volumes:
  postgres_data: